### ISSUE TITLE
Update the CSS Reset

### ISSUE THREAD

**Issue by erictompkins** [aptuitiv/cacao#11]
Compare to https://www.joshwcomeau.com/css/custom-css-reset/

Some changes like the universal box-sizing may require a new major version update.

```css
*, *::before, *::after {
  box-sizing: border-box;
}
```

Pull out `box-sizing` from any other CSS elements as it's no longer needed.
